Update Pokémon API request script to use lowercase names and streamline code

diff --git a/Advanced_shell/batchProcessing-0x02 b/Advanced_shell/batchProcessing-0x02
--- a/Advanced_shell/batchProcessing-0x02
+++ b/Advanced_shell/batchProcessing-0x02
@@ -3,30 +3,21 @@
 
 #set -x
 
-# POKEMONS=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")
+POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
 
-# for POKEMON in "${POKEMONS[@]}"; do
-#     API_URL="https://pokeapi.co/api/v2/pokemon/${POKEMON,,}"
+for POKEMON in "${POKEMONS[@]}"; do
+    API_URL="https://pokeapi.co/api/v2/pokemon/${POKEMON}"
 
-#     # Make the API request and store the response
-#     response=$(curl -s -X GET $API_URL)
+    # Make the API request and store the response
+    response=$(curl -s -X GET $API_URL)
 
-#     # Check if the curl command was successful
-#     if [ $? -ne 0 ]; then
-#         echo "Error occurred while making the API call for $POKEMON." 2> errors.txt
-#     else
-#         echo "$response" > "${POKEMON}.json"
-#     fi
+    # Check if the curl command was successful
+    if [ $? -ne 0 ]; then
+        echo "Error occurred while making the API call for $POKEMON." 2> errors.txt
+    else
+        echo "$response" > "${POKEMON}.json"
+    fi
 
-#     # Delay between requests
-#     sleep 2
-# done
-
-
-lists=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")
-
-for list in "${lists[@]}"; do
-    echo "Making API request for ${list,,}"
-    echo "..."
-    sleep 3
+    # Delay between requests
+    sleep 2
 done
